project_id = "ernfsjeedocpzmnlshqt"

[functions.send-checkout-success-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.gateway-diagnostic-hello]
verify_jwt = false
