import type { OrderItem, OrderRow } from "../supabase";
export type SalesGranularity = "daily" | "monthly" | "yearly";
export type SalesSummary = { totalRevenue: number; orderCount: number; averageOrderValue: number; productsSold: number; currency: string };
export type OrdersByStatus = { completed: number; pending: number; cancelled: number };
export type RevenuePoint = { period: string; label: string; revenue: number; orders: number };
export type TopProduct = { slug: string; name: string; quantity: number; revenue: number };
export type RecentOrder = { id: string; order_ref: string; customer_name: string; total: number; currency: string; status: string; created_at: string };
export type SalesStats = { summary: SalesSummary; ordersByStatus: OrdersByStatus; revenueSeries: RevenuePoint[]; topProducts: TopProduct[]; recentOrders: RecentOrder[] };
const COMPLETED_STATUSES = new Set(["confirmed", "shipped", "delivered", "completed"]);
const PENDING_STATUSES = new Set(["pending", "processing"]);
function safeNumber(value: unknown): number { const number = Number(value); return !Number.isFinite(number) || number < 0 ? 0 : number; }
export function countsAsRevenue(status: string): boolean { return status !== "cancelled"; }
export function getStatusBucket(status: string): keyof OrdersByStatus { if (status === "cancelled") return "cancelled"; if (PENDING_STATUSES.has(status)) return "pending"; if (COMPLETED_STATUSES.has(status)) return "completed"; return "pending"; }
function lineRevenue(item: OrderItem): number { const lineTotal = safeNumber(item.line_total_tnd); if (lineTotal > 0) return lineTotal; const quantity = safeNumber(item.qty); const unit = safeNumber(item.unit_price_tnd); const support = item.with_support ? safeNumber(item.support_unit_price_tnd) : 0; return (unit + support) * quantity; }
function orderRevenue(order: OrderRow): number { const total = safeNumber(order.total); return total > 0 ? total : (order.items ?? []).reduce((sum, item) => sum + lineRevenue(item), 0) + safeNumber(order.delivery_fee); }
function lineQuantity(item: OrderItem): number { return Math.max(0, Math.floor(safeNumber(item.qty))); }
function periodKey(iso: string, granularity: SalesGranularity): string { const date = new Date(iso); const year = date.getUTCFullYear(); const month = String(date.getUTCMonth() + 1).padStart(2, "0"); const day = String(date.getUTCDate()).padStart(2, "0"); return granularity === "yearly" ? String(year) : granularity === "monthly" ? `${year}-${month}` : `${year}-${month}-${day}`; }
function periodLabel(key: string, granularity: SalesGranularity): string { if (granularity === "yearly") return key; const parts = key.split("-"); const date = granularity === "monthly" ? new Date(Date.UTC(Number(parts[0]), Number(parts[1]) - 1, 1)) : new Date(Date.UTC(Number(parts[0]), Number(parts[1]) - 1, Number(parts[2]))); return date.toLocaleDateString("en-GB", granularity === "monthly" ? { month: "short", year: "numeric", timeZone: "UTC" } : { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }); }
function fillSeries(points: Map<string, { revenue: number; orders: number }>, from: Date, to: Date, granularity: SalesGranularity): RevenuePoint[] { const result: RevenuePoint[] = []; const cursor = new Date(from); const end = new Date(to); if (granularity === "daily") { cursor.setUTCHours(0, 0, 0, 0); end.setUTCHours(0, 0, 0, 0); } else if (granularity === "monthly") { cursor.setUTCDate(1); cursor.setUTCHours(0, 0, 0, 0); end.setUTCDate(1); end.setUTCHours(0, 0, 0, 0); } else { cursor.setUTCMonth(0, 1); cursor.setUTCHours(0, 0, 0, 0); end.setUTCMonth(0, 1); end.setUTCHours(0, 0, 0, 0); } while (cursor <= end) { const period = periodKey(cursor.toISOString(), granularity); result.push({ period, label: periodLabel(period, granularity), ...(points.get(period) ?? { revenue: 0, orders: 0 }) }); if (granularity === "daily") cursor.setUTCDate(cursor.getUTCDate() + 1); else if (granularity === "monthly") cursor.setUTCMonth(cursor.getUTCMonth() + 1); else cursor.setUTCFullYear(cursor.getUTCFullYear() + 1); } return result; }
export function computeSalesStats(orders: OrderRow[], productNames: Map<string, string>, from: Date, to: Date, granularity: SalesGranularity): SalesStats { const revenueOrders = orders.filter((order) => countsAsRevenue(order.status)); const currency = revenueOrders.find((order) => order.currency)?.currency ?? orders.find((order) => order.currency)?.currency ?? "TND"; let totalRevenue = 0; let productsSold = 0; const ordersByStatus: OrdersByStatus = { completed: 0, pending: 0, cancelled: 0 }; const seriesMap = new Map<string, { revenue: number; orders: number }>(); const productMap = new Map<string, { quantity: number; revenue: number }>(); for (const order of orders) ordersByStatus[getStatusBucket(order.status)] += 1; for (const order of revenueOrders) { const revenue = orderRevenue(order); totalRevenue += revenue; const period = periodKey(order.created_at, granularity); const bucket = seriesMap.get(period) ?? { revenue: 0, orders: 0 }; bucket.revenue += revenue; bucket.orders += 1; seriesMap.set(period, bucket); for (const item of order.items ?? []) { const quantity = lineQuantity(item); productsSold += quantity; const slug = item.slug?.trim(); if (!slug) continue; const existing = productMap.get(slug) ?? { quantity: 0, revenue: 0 }; existing.quantity += quantity; existing.revenue += lineRevenue(item); productMap.set(slug, existing); } } const orderCount = revenueOrders.length; const topProducts = [...productMap.entries()].map(([slug, stats]) => ({ slug, name: productNames.get(slug) ?? slug, quantity: stats.quantity, revenue: stats.revenue })).sort((a, b) => b.quantity - a.quantity || b.revenue - a.revenue).slice(0, 10); return { summary: { totalRevenue, orderCount, averageOrderValue: orderCount > 0 ? totalRevenue / orderCount : 0, productsSold, currency }, ordersByStatus, revenueSeries: fillSeries(seriesMap, from, to, granularity), topProducts, recentOrders: orders.slice(0, 10).map((order) => ({ id: order.id, order_ref: order.order_ref, customer_name: order.customer_name, total: orderRevenue(order), currency: order.currency || currency, status: order.status, created_at: order.created_at })) }; }
